apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud
  namespace: nextcloud-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "nextcloud"
        vault.hashicorp.com/agent-inject-secret-user.txt: "nextcloud/data/admin"
        vault.hashicorp.com/agent-inject-template-user.txt: |
          {{- with secret "nextcloud/data/admin" -}}
          {{ .Data.data.user }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-password.txt: "nextcloud/data/admin"
        vault.hashicorp.com/agent-inject-template-password.txt: |
          {{- with secret "nextcloud/data/admin" -}}
          {{ .Data.data.password }}
          {{- end }}
    spec:
      containers:
        - image: nextcloud
          name: nextcloud
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: data-volume
              mountPath: /var/www/html
          env:
            - name: SQLITE_DATABASE
              value: sqlite_nextcloud
            - name: NEXTCLOUD_ADMIN_USER_FILE
              value: /vault/secrets/user.txt
            - name: NEXTCLOUD_ADMIN_PASSWORD_FILE
              value: /vault/secrets/password.txt
      serviceAccountName: nextcloud
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 2Gi
