apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: game-2048

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kzwolenik.com
spec:
  ingressClassName: kong
  rules:
    - host: kzwolenik.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: game-2048
                port:
                  number: 80
