apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: vault
      version: "0.29.*"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 5m
  releaseName: vault
  targetNamespace: hashicorp-vault
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
