- op: add
  path: /spec/ingress/-
  value:
    from:
      - namespaceSelector:
          matchLabels:
            name: kong-namespace
      - podSelector:
          matchLabels:
            app: kong-ingress-gateway
    ports:
      - port: 3000
        protocol: TCP
