apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - resources/*.yaml

patches:
  - path: patches/grafana-config-patch.yaml
    target:
      version: v1
      kind: Secret
      name: grafana-config
      namespace: monitoring
  - path: patches/grafna-networkpolicy-patch.yaml
    target:
      version: v1
      kind: NetworkPolicy
      name: grafana
      namespace: monitoring
