apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../base
  - resources/ingress.yaml

patches:
  - path: patches/grafana-config-patch.yaml
    target:
      version: v1
      kind: Secret
      name: grafana-config
      namespace: monitoring
