apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emojivoto
  namespace: flux-system
spec:
  interval: 10m
  path: ./emojivoto-example/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
