apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: game-2048
  namespace: flux-system
spec:
  interval: 10m
  path: ./game-2048/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
