apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 10m
  path: ./nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
