apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-ingress
  namespace: flux-system
spec:
  interval: 10m
  path: ./kube-prometheus/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
