apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hashicorp-vault
  namespace: flux-system
spec:
  interval: 10m
  path: ./vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
