apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-ingress-controller
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kong-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: kong-ingress
  endpoints:
    - port: cmetrics
