apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kong-ingress-gateway
spec:
  selector:
    matchLabels:
      app: kong-ingress-gateway
  podMetricsEndpoints:
    - port: status
