apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kong-ingress-gateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kong-system
  selector:
    matchLabels:
      app: kong-ingress-gateway
  podMetricsEndpoints:
    - port: status
