apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-file-log
  annotations:
    kubernetes.io/ingress.class: kong
config:
  path: /tmp/access.log
plugin: file-log
