name: Build game

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "game-2048/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
    defaults:
      run:
        working-directory: game-2048
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            game-2048
      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ vars.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.13.0
        with:
          context: "game-2048"
          push: true
          tags: "registry.digitalocean.com/kubernetes-kzwolenik95/2048-game"
          cache-from: type=gha
          cache-to: type=gha,mode=max
