name: Run terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform-infra/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_FORCE_LOCAL_BACKEND: 1
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
      TF_VAR_admin_ip_address: ${{ vars.ADMIN_IP }}
      TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      TF_VAR_github_repository: https://github.com/${{ github.repository }}.git
      TF_VAR_github_token: ${{ secrets.FLUX_GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: terraform-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -no-color --auto-approve
